@startuml SSD

actor User
entity "Web Application" as WebApp

User -> WebApp: Get Assassin Champions

WebApp --> User: Return the list of Assassin Champions


User -> WebApp: Get List of Players that played a match

WebApp --> User: Return the list of players that played a match


User -> WebApp: Visualize Abilities of Zed

WebApp --> User: Return the visualization of Zed's abilities


User -> WebApp: Get the number of Tank Champion 

WebApp --> User: Return the count of tank champions


User -> WebApp: Get all Domination Runes

WebApp --> User: Return the list of domination runes


User -> WebApp: Get Attack Stat Objects

WebApp --> User: Return the attack stat objects


User -> WebApp: Get Ability Power Scaling Champions

WebApp --> User: Return the champions with ability power scaling


User -> WebApp: Get Rune Pages Used by Faker

WebApp --> User: Return the list of rune pages used by Faker


User -> WebApp: Get Available Game Modes

WebApp --> User: Return the list of available game modes


User -> WebApp: Get Tournaments Participated by Faker

WebApp --> User: Return the list of tournaments participated by Faker


User -> WebApp: Get Teams Played by Rekkles

WebApp --> User: Return the list of teams played by Rekkles

@enduml
